#!/bin/bash

pipeline {
    agent any

    environment {
        img = "${env.JOB_NAME}:${env.BUILD_ID}"
    }

    stages {
        stage('Checkout Code') {
            steps {
                echo "Checkout"
                sh 'ls -l'
            }
        }

        stage('Prepare Environment') {
            steps {
                echo "Prepare Environment"
                sh 'bash ./jenkinsscript.sh'
            }
        }

        stage('Run Unit Tests') {
            steps {
                echo "Running Unit Tests"
                sh '''
                    python3 -m venv myenv
                    source myenv/bin/activate
                    export PYTHONPATH=$PYTHONPATH:$(pwd)
                    pytest --cov=main utests --junitxml=./xmlReport/output.xml
                    python3 -m coverage xml
                '''
            }
        }

        stage('Publish Junit report') {
            steps {
                echo "Publish Junit Report"
                junit skipMarkingBuildUnstable: true, testResults: 'xmlReport/output.xml'
            }
        }

        stage('Publish Code Coverage') {
            steps {
                echo "Publish Code Coverage"
                cobertura coberturaReportFile: 'coverage.xml'
            }
        }

        stage('Docker Building') {
            steps {
                echo 'Docker Building Stage'
                script {
                    def img = "${env.JOB_NAME}:${env.BUILD_ID}"
                    container = docker.build(img).run('-d -p 5011:5000')
                  
                }
            }
            post {
                always {
                    script {
                        if (container) {
                            container.stop()
                        }
                    }
                }
            }
        }
    }
}
